kind: AIchorManifest
apiVersion: 0.2.2

builder:
  image: image
  context: smoke-test # smoke-test folder
  dockerfile: ./build/Dockerfile

spec:
  operator: batchjob
  image: image
  command: >
    bash src/test_pvc2.sh

  tensorboard:
    enabled: true

 # storage:
 #   attachExistingPVCs:
 #     - name: testprojpvc-af7b62643072486e-andanotheron-19b831fed72c429e
 #       mountPoint: /mnt/testprojpvc-af7b62643072486e-andanotheron-19b831fed72c429e

  types:
    Worker:
      count: 1
      resources:
        cpus: 1
        ramRatio: 2
        shmSizeGB: 0

