kind: AIchorManifest
apiVersion: 0.2.2

builder:
  image: image
  context: pytorch-demo
  dockerfile: ./Dockerfile

spec:
  operator: pytorch
  image: image
  command:  >
    bash test_pvc.sh


  tensorboard:
    enabled: true
  storage:
    attachExistingPVCs:
      - name: testprojpvc-af7b62643072486e-test-0fae16c22bfc4f47
        mountPoint: /mnt/testprojpvc-af7b62643072486e-test-0fae16c22bfc4f47


  types:
    Master:
      count: 1
      resources:
        cpus: 1
        ramRatio: 2
    Worker:
      count: 1
      resources:
        cpus: 1
        ramRatio: 2

